

Description: Launch Configuration 

Parameters: 
  #-------------
  # LC 
  
  SGName:
    Description: Name security group
    Type: String 

  EFSName:
    Description: Id EFS
    Type: String


Resources:
  LaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: ami-0b37e9efc396e4c38
      SecurityGroups: 
        - !Ref SGName 
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt-get update
            sudo apt-get install awscli -y
            sudo apt update
            sudo apt install nginx -y

            sudo apt-get install nfs-common
            git clone https://github.com/aws/efs-utils
            cd efs-utils
            sudo apt-get update
            sudo apt-get -y install binutils
            sudo ./build-deb.sh
            sudo apt-get -y install ./build/amazon-efs-utils*deb

            cd /var/www/
            sudo mount -t efs ${EFSName}:/ /var/www/html/
            systemctl start nginx
            echo "<html><h1> Hola mundo </h1></html>" >> /var/www/html/index.html
            
Outputs:
  idLC:
    Description: Id del LC
    Value: !Ref LaunchConfig