Description: "Template que genera una VPC, un EFS ..."

Parameters: 

  #+------------------------------------------------------------------
  #|  ARCHIVO VPC.yaml
  #+------------------------------------------------------------------

  #-------------
  # VPC
  VPCName:
    Description: "Nombre de la VPC a crear."
    Type: String
    Default: "vpc_joseph"
    
Resources:

  #-------------
  # VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref VPCName
      TemplateURL: https://bckt-joseph.s3-us-west-2.amazonaws.com/Ejerccio5/VPC/vpc.yaml 

  #-------------
  # EFS

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC: !GetAtt 'VPC.Outputs.idVPC'
        Subnet6: !GetAtt 'VPC.Outputs.IdSubRed6'
      TemplateURL: https://bckt-joseph.s3-us-west-2.amazonaws.com/Ejerccio5/EFS/efs.yaml 
