Description: "Template que genera una VPC, un EFS ..."

Parameters: 

  #+------------------------------------------------------------------
  #|  ARCHIVO VPC.yaml
  #+------------------------------------------------------------------

  #-------------
  # VPC
  VPCName:
    Description: Nombre de la VPC a crear.
    Type: String
    Default: vpc_joseph

  #+------------------------------------------------------------------
  #|  ARCHIVO EFS.yaml
  #+------------------------------------------------------------------

  BucketName:
    Description: Bucket name where the templates are located
    Type: String
    Default: bckt-joseph.s3-us-west-2.amazonaws.com
Resources:

  #-------------
  # VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref VPCName
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/VPC/vpc.yaml 

  #-------------
  # EFS

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC: !GetAtt 'VPC.Outputs.idVPC'
        Subnet6: !GetAtt 'VPC.Outputs.IdSubRed6'
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/EFS/efs.yaml 

  #-------------
  # Launch Configuration
  
  LaunchConfig:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        SGName: !GetAtt 'EFS.Outputs.idSecurityGroup'
        EFSName: !GetAtt 'EFS.Outputs.idEFS'
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/LC/lc.yaml

  #-------------
  # Load Balancer
  
  LoadBalancer:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet6: !GetAtt 'VPC.Outputs.IdSubRed6'
        SGName: !GetAtt 'EFS.Outputs.idSecurityGroup'
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/LB/lb.yaml

  
  #-------------
  # Auto Scaling Group
  
  WebServerGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Subnet4: !GetAtt 'VPC.Outputs.IdSubRed4'
        Subnet5: !GetAtt 'VPC.Outputs.IdSubRed5'
        Subnet6: !GetAtt 'VPC.Outputs.IdSubRed6'
        LBName: !GetAtt 'LoadBalancer.Outputs.idLB'
        LCName: !GetAtt 'LaunchConfig.Outputs.idLC'
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/AG/ag.yaml

  