Description: "Template que genera una VPC, un EFS ..."

Parameters: 

  #+------------------------------------------------------------------
  #|  ARCHIVO VPC.yaml
  #+------------------------------------------------------------------

  #-------------
  # VPC
  VPCName:
    Description: Nombre de la VPC a crear.
    Type: String
    Default: vpc_joseph

  #+------------------------------------------------------------------
  #|  ARCHIVO EFS.yaml
  #+------------------------------------------------------------------

  BucketName:
    Description: Bucket name where the templates are located
    Type: String
    Default: bckt-joseph.s3-us-west-2.amazonaws.com
Resources:

  #-------------
  # VPC
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref VPCName
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/VPC/vpc.yaml 

  #-------------
  # EFS

  EFS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC: !GetAtt 'VPC.Outputs.idVPC'
        Subnet6: !GetAtt 'VPC.Outputs.IdSubRed6'
      TemplateURL: !Sub https://${BucketName}/Ejerccio5/EFS/efs.yaml 
