Description: Create a EFS

Parameters: 
  #-------------
  # VPC
  VPC:
    Description: VPC ID
    Type: String 

  Subnet6:
    Description: public subnet
    Type: String 

  #-------------
  # Security Group
  SGName:
    Description: Security group name
    Type: String
    Default: sg_joseph

  #-------------
  # EFS
  EFSName:
    Description: Name file system
    Type: String
    Default: efs_joseph

Resources:

  #-------------
  # Security group

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Puertos 22, 80 y 2049
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '2049'
        ToPort: '2049'
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref 'SGName' 

  #-------------
  # EFS
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      PerformanceMode: generalPurpose
      FileSystemTags:
        - Key: Name
          Value: !Ref 'EFSName' 

          
  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !Ref Subnet6
      SecurityGroups: 
        - !Ref InstanceSecurityGroup

Outputs:
  idEFS:
    Description: Id EFS
    Value: !Ref FileSystem 
  idSecurityGroup:
    Description: Id security group
    Value: !Ref InstanceSecurityGroup 
