
Description: Auto scaling group

Parameters: 
  #-------------
  # public subnets

  Subnet4:
    Description: Public subnet
    Type: String 

  Subnet5:
    Description: Public subnet
    Type: String 

  Subnet6:
    Description: Public subnet 
    Type: String 

  #-------------
  # Load Balancer 
  LBName:
    Description: Id loadbalancer
    Type: String 

  #-------------
  # Launch Configuration
  LCName:
    Description: Id Launch Configuration
    Type: String 

Resources:

  WebServerGroup: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      LaunchConfigurationName: !Ref LCName
      MinSize: 2
      MaxSize: 2
      DesiredCapacity: 2
      LoadBalancerNames: 
        - !Ref LBName
      VPCZoneIdentifier: 
        - !Ref Subnet6